name: CI Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

env:
  PROJECT_ID: treasure-hunt-storage
  GAR_LOCATION: us-central1
  SERVICE: sheba-service-gcp
  REGION: us-central1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
